version: "3"
services:
    web:
        build: .
        image: split-api
        container_name: split-api
        restart: always
        ports:
            - "11512:11512" 

networks:
    default:
        name: proxy_default
        external: true
